In [2]:
import pandas as pd
import numpy as np

EJERCICIO 1

¿Qué diferencia hay entre una Serie y un DataFrame?

In [3]:
# Serie unidimensional y array puede ser ser bidimensional o tridimensional

In [4]:
datos=np.empty((4,3))

In [5]:
paises = ["españa","francia","italia"]


serie_paises = pd.Series(paises)
serie_paises

0     españa
1    francia
2     italia
dtype: str

In [6]:


datos=np.empty((4,3))


columnas = ['ESPAÑA', 'ITALIA', 'FRANCIA']

df = pd.DataFrame(datos, columns=columnas)

print(df)

          ESPAÑA         ITALIA        FRANCIA
0  7.543959e-312  3.162020e-322   0.000000e+00
1   0.000000e+00   0.000000e+00   1.188070e-75
2   8.672270e-67  2.230447e+160  1.731908e+185
3   8.605341e-67   5.640068e-38   4.857873e-33

In [22]:
#Descarga el archivo "medallas" y carga el DataFrame.

pd.read_csv('Files/medallas.csv')

   Unnamed: 0             País   Oro  Plata  Bronce
0           1            China  1473    994     720
1           2            Japón  1032   1037     985
2           3    Corea del Sur   745    663     827
3           4             Irán   179    181     197
4           5       Kazajistán   155    158     224
5           6            India   154    202     315
6           7        Tailandia   132    175     278
7           8        Indonesia   112    131     240
8           9     China Taipéi    99    144     276
9          10  Corea del Norte    91    120     235

In [23]:
df_csv=pd.read_csv('Files/medallas.csv')

In [ ]:
# Usando el loc extrae todas las columnas de la fila de Tailandia.
df_csv.loc[6]

   Unnamed: 0   País   Oro  Plata  Bronce
0           1  China  1473    994     720
3           4   Irán   179    181     197

In [ ]:
# Usando el loc extrae todas las columnas de China e Irán.

df_csv.loc[[0,3]]

In [33]:
# Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
df_csv.loc[[0,3],['País','Oro','Plata','Bronce']]

    País   Oro  Plata  Bronce
0  China  1473    994     720
3   Irán   179    181     197

In [38]:
#Usando el iloc extrae la información de la India. Devolved todas las columnas.
df_csv.iloc[5]

Unnamed: 0        6
País          India
Oro             154
Plata           202
Bronce          315
Name: 5, dtype: object

In [ ]:
# Usando el iloc extrae todas las columnas de los países que estén en posición impar. 
# La primera que nos tendría que salir es Japón y la última Corea del Norte.
df_csv.iloc[5]